name = "creator-api-worker"
main = "src/index.js"
compatibility_date = "2026-09-28"

[vars]
AUTH_KEY = "gas"

[[d1_databases]]
binding = "DB"
database_name = "ielts-diary-db"
database_id = "31e14c59-f641-416f-843d-ce5d988d2f89"
